networks:
  default: development

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

compiler:
  solc:
    version: 0.8.4
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

